version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install npm packages
          command: cd CHAP14/appdemo && npm install
      - run: 
          name: Run npm build
          command: cd CHAP14/appdemo && npm run build
      - run: 
          name: Execute tests
          command: cd CHAP14/appdemo && npm run test